### ISSUE TITLE
Support for Jaeger formatted traces??

### ISSUE THREAD

**Issue by notcool11** [signalfx/signalfx-dotnet-tracing#129]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : All
- Library type: All
- Library version: All

**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Currently there are only Zipkin and OpenTelemetry propagators. Would like to know if there is roadmap for supporting Jaeger??

**Describe alternatives you've considered**
The OpenTelemetry dotnet SDK doesn't have a Jaeger propagator either, so either why it looks like I'll have some hand-rolling to do before I can use these libraries with Jaeger.

**Additional context**
Looks like a Jaeger Propagator [would go here](https://github.com/signalfx/signalfx-dotnet-tracing/tree/main/src/Datadog.Trace/Propagation). Would also need to update the builder to be aware of the new type. Am I on the right path?? Thanks.

**Comment by pjanotti** [comment]
Sorry I missed this earlier @notcool11. Yes, you are on the right path that said we don't have it on our roadmap. If you submit a PR here or on OTel we can help reviewing it. Let us know if you have further questions.

**Comment by pellared** [comment]
Stale issue. Closing
