### ISSUE TITLE
Support built-in .NET OpenTelemetry classes

### ISSUE THREAD

**Issue by ccurrens** [signalfx/signalfx-dotnet-tracing#434]
The .NET has had support for OpenTelemetry traces and spans since .NET Core 2.0. It is a way to instrument code without needing a dependency on a particular version of OpenTelemetry.

**Describe the solution you'd like**
This project should automatically register an `ActivityListener` (e.g. `ActivitySource.AddActivityListener`) and export those traces/spans to splunk.

**Describe alternatives you've considered**
Adding my own activity listener. This doesn't work well, since it seems to require creating a new span inside of OpenTracing, and we can't share the existing span ID that is generated by the `ActivitySource`

**Additional context**
See https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs

**Comment by RassK** [comment]
Proper OpenTelemetry support moved > https://github.com/signalfx/splunk-otel-dotnet
