### ISSUE TITLE
OpenTracing library is deprecated

### ISSUE THREAD

**Issue by ccurrens** [signalfx/signalfx-dotnet-tracing#435]
OpenTracing is deprecated. Currently the documentation instructs developers to use OpenTracing to add manual instrumentation. Perhaps the tracer in [opentelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet) should be used

Using the API built-in to .NET could also be a solution here. (#434). 

**Additional context**
From the About section on the project's github -- https://github.com/opentracing/opentracing-csharp:
>>>
    _OpenTracing API for C# (.NET). 🛑 This library is DEPRECATED! https://github.com/opentracing/specification/issues/163_
>>>
[Documentation about the built-in .NET Activity class in the  opentelemetry-dotnet project](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/getting-started/README.md#opentelemetry-net-and-relation-with-net-activity-api)

**Comment by pellared** [comment]
We are aware of it.
We are actively involved in the development of https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation.
