### ISSUE TITLE
SignalFx.Tracing.dll strong name validation fails, asp.net unable to start

### ISSUE THREAD

**Issue by nfaulk** [signalfx/signalfx-dotnet-tracing#56]
**Describe the bug**
SignalFx.Tracing strong name validation fails, asp.net unable to start

**To Reproduce**
1. Create a new ASP.NET Web Application (Replicated on on .NET framework 4.5, 4.6 and 4.7.1)
2. Add the SignalFx.Tracing.OpenTracing nuget package
3. Run the project (IIS or IIS Express)

`Could not load file or assembly 'SignalFx.Tracing' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

=== Pre-bind state information ===
LOG: DisplayName = SignalFx.Tracing
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: SignalFx.Tracing | Domain ID: 2
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///C:/src/WebApplication1/WebApplication1/
LOG: Initial PrivatePath = C:\src\WebApplication1\WebApplication1\bin
Calling assembly : (Unknown).`

**This issue is not present in SignalFx.Tracing.OpenTracing v0.1.2. Anything later (0.1.3 - 0.1.5) fails**
Doesn't seem to be an issue with .NET core runtimes

**Runtime environment:**
Windows 10 pro 1909
.NET 4.8.03752

**Comment by pjanotti** [comment]
Thanks for reporting @narth.

**Comment by pjanotti** [comment]
Hi @nfaulk release 0.1.6 is available now with proper strong name signature.
