### ISSUE TITLE
Invalid URL in documentation due to changes in release routines.

### ISSUE THREAD

**Issue by torjue** [signalfx/signalfx-dotnet-tracing#69]
**Describe the bug**
After release 0.1.2, you've started to include the version number in the file name of the artifacts. This creates an issue if you follow the instructions given in the README.md, where you link to the `latest` version.

https://github.com/signalfx/signalfx-dotnet-tracing/blob/f78d20aa72229d5aebc3ae3b4f9b76e5adfa6b8a/README.md#L141-L145

**To Reproduce**
Run the command given in the documentation.

**Expected behavior**
To not include the version number.

**Screenshots**
n/a

**Runtime environment (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by pjanotti** [comment]
Thanks for pointing this out @torjue. I will address it together with the new release (#71).
