### ISSUE TITLE
Build new CF buildpacks versions on new release

### ISSUE THREAD

**Issue by mateuszrzeszutek** [signalfx/signalfx-dotnet-tracing#72]
The aim of this task is to include the CF buildpacks introduced in #67 in the release process. Both buildpacks could be built on the Circle CI automatically whenever a new version is released. The resulting zip files should be attached to the release as an asset.

See: https://github.com/signalfx/signalfx-dotnet-tracing/pull/67

**Comment by flands** [comment]
@mateuszrzeszutek can this be closed?

**Comment by mateuszrzeszutek** [comment]
It's not done yet. But if we don't want to waste any time or resources on automatic CF buildpack release (which might not be that necessary) it's fine if we just close it.

**Comment by RassK** [comment]
Old stale issue.
